"""Renders docs/prds/catalog/PRD-XXXX.md files and PRD_INDEX.md from prd_catalog_data.json.

Re-run with `uv run python tools/generate_prd_catalog.py` after editing the JSON data
file to regenerate the catalog. This script intentionally contains no business logic —
it only templates markdown from already-curated data (kept <=150 lines per project rule).
"""

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "tools" / "prd_catalog_data.json"
CATALOG_DIR = ROOT / "docs" / "prds" / "catalog"
INDEX_PATH = ROOT / "docs" / "prds" / "PRD_INDEX.md"

TEMPLATE = """# {prd_id} — {title}

- **PRD ID**: {prd_id}
- **Title**: {title}
- **Category**: {category}
- **Requirement source**: {source}
- **Implementation chunk**: {chunk}
- **Status**: {status}

## Requirement statement

{statement}

## Rationale

{rationale}

## Acceptance criteria

{acceptance}

## Test / validation method

{test_method}
"""


def render_prd(prd_id: str, item: dict) -> str:
    return TEMPLATE.format(prd_id=prd_id, **item)


def render_index(grouped: dict) -> str:
    lines = [
        "# PRD Catalog Index",
        "",
        "Auto-generated by `tools/generate_prd_catalog.py` from `tools/prd_catalog_data.json`. "
        "Do not hand-edit this file — edit the JSON data and re-run the generator instead.",
        "",
        f"Total catalog PRDs: **{sum(len(v) for v in grouped.values())}**",
        "",
    ]
    for category in sorted(grouped):
        entries = grouped[category]
        lines.append(f"## {category} ({len(entries)})")
        lines.append("")
        for prd_id, title in entries:
            lines.append(f"- [{prd_id}](catalog/{prd_id}.md) — {title}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    items = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    CATALOG_DIR.mkdir(parents=True, exist_ok=True)

    grouped: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for index, item in enumerate(items, start=1):
        prd_id = f"PRD-{index:04d}"
        out_path = CATALOG_DIR / f"{prd_id}.md"
        out_path.write_text(render_prd(prd_id, item), encoding="utf-8")
        grouped[item["category"]].append((prd_id, item["title"]))

    INDEX_PATH.write_text(render_index(grouped), encoding="utf-8")
    print(f"Generated {len(items)} catalog PRDs in {CATALOG_DIR}")
    print(f"Generated index at {INDEX_PATH}")


if __name__ == "__main__":
    main()
